### ISSUE TITLE
Add this repo to ustwo.github.io? 

### ISSUE THREAD

**Issue by mikaelha** [ustwo/bdd-crossplatform-apps#92]
@emmaguy - Would this be a good candidate to add to our github.io profile? You can have a chat with @simonlindsay if you like to get it in there and we can help you with that.

**Comment by emmaguy** [comment]
@mikaelha yes - that sounds like it'd be good - I'll say hi to @simonlindsay to get the ball rolling :smile:

**Comment by simonlindsay** [comment]
Added repo to http://ustwo.github.io, awaiting images from @emmaguy

**Comment by emmaguy** [comment]
How about this @simonlindsay ?

<img width="264" alt="preview" src="https://cloud.githubusercontent.com/assets/1143801/8908929/ac79921a-3476-11e5-96a9-4fae1b08bbac.png">

**Comment by juandelgado** [comment]
@emmaguy while you are at it, the BDD repo could do with a link to the post on the ustwo blog!

**Comment by simonlindsay** [comment]
Updated on http://ustwo.github.io/
